# Generated by Django 4.2.2 on 2023-06-30 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ghec_app', '0003_application'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='amount_paid',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.AlterField(
            model_name='application',
            name='debt',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.AlterField(
            model_name='application',
            name='processing_fee',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
    ]
