# Generated by Django 4.2.2 on 2023-07-14 14:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ghec_app', '0004_alter_application_amount_paid_alter_application_debt_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='client_name',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
