# Generated by Django 4.2.2 on 2023-07-15 02:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ghec_app', '0005_alter_application_client_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Receipt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount_paid', models.CharField(blank=True, choices=[('Brazil', 'Brazil'), ('Canada', 'Canada'), ('Turkey', 'Turkey'), ('USA', 'USA')], max_length=120, null=True)),
                ('date_paid', models.DateField()),
                ('sender_name', models.CharField(max_length=100)),
                ('bank_name', models.CharField(max_length=100)),
                ('reason', models.CharField(blank=True, choices=[('Canada Schooling', 'Canada Schooling'), ('Canada Express Entry', 'Canada Express Entry'), ('Canada Tourism', 'Canada Tourism'), ('Canada Business', 'Canada Business'), ('USA Schooling', 'USA Schooling'), ('USA Express Entry', 'USA Express Entry'), ('USA Tourism', 'USA Tourism'), ('USA Business', 'USA Business'), ('USA Birth Services', 'USA Birth Services'), ('Brazil Birth Services', 'Brazil Birth Services'), ('Barbados Birth Services', 'Barbados Birth Services'), ('Turkey Schooling', 'Turkey Schooling'), ('Turkey Tourism', 'Turkey Tourism'), ('Turkey Business', 'Turkey Business')], max_length=120, null=True)),
                ('client_name', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
